apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-app-pv
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/frontend-data  # local folder on your laptop

# In k3d: PV usually uses hostPath on your laptop.
