apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app-pvc
  namespace: team1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard 


# In GKE, standard automatically provisions a Persistent Disk, so don’t need to manually create a PV
# In k3d/local, it needs a PV with hostPath since no cloud storage exists
